### ISSUE TITLE
controller比SuffixOpParamFilter过滤器先执行

### ISSUE THREAD

**Issue by Gelilory** [troyzhxu/bean-searcher#100]
我同时打开了SuffixOpParamFilter、JsonArrayParamFilter
发现controller比SuffixOpParamFilter过滤器先执行，导致id-il类似的参数无法识别。请问是什么原因

**Comment by troyzhxu** [comment]
参数过滤器 `SuffixOpParamFilter` 是在调用 Bean Searcher 的检索器的 `searchXxx(..)` 方法里才会执行的。
你遇到这个问题，调用  `searchXxx(..)` 方法时传入的参数都有哪些呢？

**Comment by Gelilory** [comment]
我又检查了代码，发现xxx-il是可以被解析，xxx-bt无法被解析为between区间查询
我使用的search()方法传参如下，start-bt无法被解析为between区间查询,而是被解析成为starttm>=?
![image](https://github.com/user-attachments/assets/92f648a0-c83f-43f5-b16c-c04e5db81c33)
![image](https://github.com/user-attachments/assets/4689e2f9-8aff-4578-9d85-cf8f3caa45f3)

**Comment by troyzhxu** [comment]
你的截图里传的就是 `starttm-bt`，没有传 `start-bt` 呀

**Comment by Gelilory** [comment]
我描述错了,是starttm-bt无法解析为between区间查询条件

**Comment by troyzhxu** [comment]
> 我描述错了,是starttm-bt无法解析为between区间查询条件

只有 [条件属性](https://bs.zhxu.cn/guide/bean/fields.html) 才能这么用，在你的 `XcRecords` 类里有 `starttm` 这个条件属性吗？截图看一下。

**Comment by Gelilory** [comment]
前端传参如下图
![image](https://github.com/user-attachments/assets/b034a2c7-153e-41b2-a952-abe0bac86acc)

开启bean search参数过滤器相关配置
![image](https://github.com/user-attachments/assets/de18d18f-3504-4b10-afde-38b68a025fcd)

Vo类代码如下
![image](https://github.com/user-attachments/assets/0b3e7659-d6cf-4cac-89c7-091cccf21419)

Controller代码如下图，使用@RequestBody接收参数
![image](https://github.com/user-attachments/assets/bb554106-dde6-4298-8c88-34889039a32b)

ServiceImpl代码如下图，将接收到的map直接传入search()方法
![image](https://github.com/user-attachments/assets/f39f6ee5-4d03-4828-ac2d-fe7213c0433b)

最终解析生成的sql，并不是between区间查询条件
![image](https://github.com/user-attachments/assets/badfbece-ae52-4d79-8816-c781610a6c81)

**Comment by troyzhxu** [comment]
参数值给错了，启用了 `JsonArrayParamFilter` 后，`starttm_bt` 的值应该传 **JSON数组字符串**，而不是 **JSON 数组对象**

**Comment by Gelilory** [comment]
starttm_bt参数改为字符串了，还是无法解析成between区间查询条件
![image](https://github.com/user-attachments/assets/87ce7076-fac5-4894-9835-a2cc2f617385)
![image](https://github.com/user-attachments/assets/a2bbf2c4-1e3b-4db3-887f-1520be93be31)
![image](https://github.com/user-attachments/assets/f5e7d59e-8ca6-4a0f-bd40-bf46a3442f7c)

**Comment by Gelilory** [comment]
我后来使用自定义sql条件,替代实现时间区间查询
![image](https://github.com/user-attachments/assets/adb5399d-5721-4c5a-a560-0a7f8ba304d0)
![image](https://github.com/user-attachments/assets/5ac6c414-4649-48bf-8871-b159b7c181bf)

**Comment by troyzhxu** [comment]
日期格式给错误了，'["2024-08-01", "2024-09-01"]'，你写成了 '["2024-8-1", "2024-9-1"]'，少了 2 个 0

**Comment by troyzhxu** [comment]
新版本 `v4.3.5` 已支持了 ["2024-8-1", "2024-9-1"] 这种日期格式：https://github.com/troyzhxu/bean-searcher/releases/tag/v4.3.5
