### ISSUE TITLE
默认参数与后端参数有相同字段如何处理啊？

### ISSUE THREAD

**Issue by dazhaozhao** [troyzhxu/bean-searcher#102]
如图
<img width="704" alt="image" src="https://github.com/user-attachments/assets/40e1a80c-123f-4460-b35a-ca68d22dce4e">

**Comment by troyzhxu** [comment]
这得看你想要这个 “默认参数” 生成什么条件，想要这个条件与其它条件之间是什么样的关系。想清楚这些后，在调用对应的方法即可。你可以举个具体的例子。

**Comment by dazhaozhao** [comment]
> 这得看你想要这个 **“默认参数”** 生成什么条件，想要这个条件与其它条件之间 形成 什么样的 **逻辑关系**。搞清楚这些后，再调用对应的方法即可。你可以举个具体的例子。

我是前端传入name=1,后端还要限制下name in (1,2,3) 结果sql 里好像只有name in (1,2,3)了 ，目前我使用了附加字段解决了这个问题 略显冗余了。。。

**Comment by dazhaozhao** [comment]
> > 这得看你想要这个 **“默认参数”** 生成什么条件，想要这个条件与其它条件之间 形成 什么样的 **逻辑关系**。搞清楚这些后，再调用对应的方法即可。你可以举个具体的例子。
> 
> 我是前端传入name=1,后端还要限制下name in (1,2,3) 结果sql 里好像只有name in (1,2,3)了 ，目前我使用了附加字段解决了这个问题 略显冗余了。。。
var map = new HashMap<>()
map.put("name",1)
如何让MapUtils.builder(map).field("name").sql("$1 in (1,2,3)")中的map 与后续的分组隔开？

**Comment by dazhaozhao** [comment]
> > 这得看你想要这个 **“默认参数”** 生成什么条件，想要这个条件与其它条件之间 形成 什么样的 **逻辑关系**。搞清楚这些后，再调用对应的方法即可。你可以举个具体的例子。
> 
> 我是前端传入name=1,后端还要限制下name in (1,2,3) 结果sql 里好像只有name in (1,2,3)了 ，目前我使用了附加字段解决了这个问题 略显冗余了。。。

var map = new HashMap<>()
map.put("name",1)
如何让MapUtils.builder(map).field("name").sql("$1 in (1,2,3)")中的map 与后续的分组隔开？

**Comment by troyzhxu** [comment]
```
var name = "前端传来的值";
var params = MapUtils.builder(map)
    .field("name").sql("$1 in (1,2,3) and $1 = ?", name)
   .build();
```

**Comment by dazhaozhao** [comment]
> 也可以让前端传参使用 逻辑分组：
> 
> ```java
> // 模拟前端传参
> var map = new HashMap<>();
> map.put("A.name", 1);
> map.put("gexpr", "A");
> 
> // 这样就不会被参数构建器覆盖
> 
> var params = MapUtils.builder(map)
>     .field("name").sql("$1 in (1,2,3)")
>     .build();
> ```

这个可能需要我遍历map 给每个key 加一个A. 也行吧，我以为map里的参数自带一个分组
