### ISSUE TITLE
超出 max page offset 怎么解决？

### ISSUE THREAD

**Issue by dazhaozhao** [troyzhxu/bean-searcher#104]
<img width="1612" alt="image" src="https://github.com/user-attachments/assets/07177fa7-99cd-4f1e-9328-aa7f20d6b31e">

**Comment by troyzhxu** [comment]
可配置：https://bs.zhxu.cn/guide/advance/safe.html#%E9%A3%8E%E6%8E%A7%E9%85%8D%E7%BD%AE%E9%A1%B9
