### ISSUE TITLE
同一个字段多个查询条件，为什么只有最后一个生效

### ISSUE THREAD

**Issue by dazhaozhao** [troyzhxu/bean-searcher#108]
`
  MapUtils.builder().field("A").sql("locate($1,'xxxx')>0").field("A").sql("length($1)=5").build()
`
结果SQL 只有 
` length(A)=5`
<img width="783" alt="image" src="https://github.com/user-attachments/assets/7a686957-18e5-462f-837b-6eac314fd070">
有简化，咋个关闭简化？

**Comment by troyzhxu** [comment]
同一个组内，同一个字段，`field(..)` 只会生效一次，你可以把它合并在一起：

```java
MapUtils.builder()
        .field("A").sql("locate($1,'xxxx')>0 and length($1)=5")
        .build()
```
或者：
```java
MapUtils.builder()
        .field("A").sql("locate($1,'xxxx')>0 or length($1)=5")
        .build()
```

**Comment by troyzhxu** [comment]
> 有简化，咋个关闭简化？

目前尚未提供取消自动化简的功能。你为何要取消呢，可以描述一下你的使用场景 以及 取消的意义吗？

**Comment by dazhaozhao** [comment]
> 同一个组内，同一个字段，`field(..)` 只会生效一次，你可以把它合并在一起：
> 
> ```java
> MapUtils.builder()
>         .field("A").sql("locate($1,'xxxx')>0 and length($1)=5")
>         .build()
> ```
> 
> 或者：
> 
> ```java
> MapUtils.builder()
>         .field("A").sql("locate($1,'xxxx')>0 or length($1)=5")
>         .build()
> ```

是这样的，这个条件不是在一个地方定好的，是动态拼接的，可能在方法A里需要使用locate限定 其他方法使用length 限定

**Comment by dazhaozhao** [comment]
> > 有简化，咋个关闭简化？
> 
> 目前尚未提供取消自动化简的功能。你为何要取消呢，可以描述一下你的使用场景 以及 取消的意义吗？

目前简化 下 假设有三个条件，就会有两个丢失了，你上面说的，合并在一个条件下，目前我们也是动态凭借的查询条件，多个业务方法之间对同一个字段的限定也不太能合并起来的...

**Comment by troyzhxu** [comment]
> > 同一个组内，同一个字段，`field(..)` 只会生效一次，你可以把它合并在一起：
> > ```java
> > MapUtils.builder()
> >         .field("A").sql("locate($1,'xxxx')>0 and length($1)=5")
> >         .build()
> > ```
> >   
> > 或者：
> > ```java
> > MapUtils.builder()
> >         .field("A").sql("locate($1,'xxxx')>0 or length($1)=5")
> >         .build()
> > ```
> 
> 是这样的，这个条件不是在一个地方定好的，是动态拼接的，可能在方法A里需要使用locate限定 其他方法使用length 限定

那可以再定义一个 field:

```java
@DbField("length(A字段)")
private Integer length;
```

**Comment by troyzhxu** [comment]
> > > 有简化，咋个关闭简化？
> > 
> > 
> > 目前尚未提供取消自动化简的功能。你为何要取消呢，可以描述一下你的使用场景 以及 取消的意义吗？
> 
> 目前简化 下 假设有三个条件，就会有两个丢失了，你上面说的，合并在一个条件下，目前我们也是动态凭借的查询条件，多个业务方法之间对同一个字段的限定也不太能合并起来的...

同一个逻辑组下的同一个 field，只能添加一次条件，这和 逻辑组表达式的自动化简 是没有关系的。
