### ISSUE TITLE
如何使用代码进行配置，而不是使用yml或properties？

### ISSUE THREAD

**Issue by blackknifes** [troyzhxu/bean-searcher#111]
另外问一下，有没有交流群？有些在官网找不到的问题想在群众及时交流获取解放方法。

**Comment by troyzhxu** [comment]
参考 `bean-searcher-boot-starter` 里的 `BeanSearcherAutoConfiguration`，代码配置响应的 Bean 即可。

交流群：

![image](https://github.com/user-attachments/assets/eaec754e-3a48-4e26-af43-bad9011647f6)
