### ISSUE TITLE
建议增加类似注解(JsonField)，以达成json字符串自动转对象功能，注意：json分为两种对象模式，1 对象{} 2集合[{}]

### ISSUE THREAD

**Issue by humlzy** [troyzhxu/bean-searcher#20]
/**
     * Delivery Profile
     */
    @JsonField("delivery_profile")
    private DeliveryProfile deliveryProfile;

    /**
     * Consignment
     */
    @JsonField("consignment")
    private List<Consignment> consignment;

**Comment by ejlchina** [comment]
这可以通过添加一个自定义自段转换器来实现：
https://searcher.ejlchina.com/guide/latest/advance.html#%E5%AD%97%E6%AE%B5%E8%BD%AC%E6%8D%A2%E5%99%A8

**Comment by troyzhxu** [comment]
v4.0 开始，已新增了 JSON 转换器：
https://github.com/troyzhxu/bean-searcher/releases/tag/v4.0.0.alpha3
