### ISSUE TITLE
后端的Javabean还得定义，如果依据前端的参数 建议能能自动生成查询sql，

### ISSUE THREAD

**Issue by kiwimg** [troyzhxu/bean-searcher#37]
后端的Javabean还得定义，如果依据前端的参数，前端描述怎么查询方式，后端生成自动生成查询sql，我理解这是最好的方式，开发速度更快，

**Comment by troyzhxu** [comment]
这很容易：前端传 SQL 字符串，后端拿到 SQL 字符串用 Jdbc 直接执行并返回结果，就是你所期望的了。

然而 Bean Searcher 并不会这么做，因为前端无所不能并不是一件好事。
