### ISSUE TITLE
字段如何只作为查询条件，不参与查询结果

### ISSUE THREAD

**Issue by mymy1026** [troyzhxu/bean-searcher#61]
目前我遇到了这样的需求，主表 root 和 字表leaf是一对多的关系，我想查询主表root时关联leaf表的字段作为限制条件。我如果把leaf子表的字段做DBField数据库映射的话会导致主表root数据重复，leaf子表参与限制的条件不一定存在，请教大佬有什么解决办法吗

**Comment by troyzhxu** [comment]
* 方法1，使用 where 子查询配合 嵌入参数：
https://bs.zhxu.cn/guide/latest/bean.html#where-%E5%AD%90%E6%9F%A5%E8%AF%A2
https://bs.zhxu.cn/guide/latest/bean.html#%E5%B5%8C%E5%85%A5%E5%8F%82%E6%95%B0

* 方法2，使用 groupBy，主表字段都加入 groupBy 里，子表条件放在 where 里配合 嵌入参数
https://bs.zhxu.cn/guide/latest/bean.html#group-by-%E5%88%86%E7%BB%84-%E4%B8%8E-%E8%81%9A%E5%90%88%E5%87%BD%E6%95%B0

**Comment by troyzhxu** [comment]
v4.1.0 开始，注解 `@SearchBean` 新增了 `fields` 属性，它声明的字段 只会作为 查询条件，不参与查询结果。
