### ISSUE TITLE
分页查询totalCount过大造成OOM

### ISSUE THREAD

**Issue by xiejinsong** [troyzhxu/bean-searcher#62]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.ArrayList.<init>(ArrayList.java:153)
	at com.ejlchina.searcher.SearchResult.<init>(SearchResult.java:32)
	at com.ejlchina.searcher.implement.DefaultBeanSearcher.search(DefaultBeanSearcher.java:69)
	at com.ejlchina.searcher.implement.DefaultBeanSearcher.search(DefaultBeanSearcher.java:32)

    /**
     * Constructs an empty list with the specified initial capacity.
     *
     * @param  initialCapacity  the initial capacity of the list
     * @throws IllegalArgumentException if the specified initial capacity
     *         is negative
     */
    public ArrayList(int initialCapacity) {
        if (initialCapacity > 0) {
            this.elementData = new Object[initialCapacity];
        } else if (initialCapacity == 0) {
            this.elementData = EMPTY_ELEMENTDATA;
        } else {
            throw new IllegalArgumentException("Illegal Capacity: "+
                                               initialCapacity);
        }
    }

**Comment by troyzhxu** [comment]
totalCount 不会造成 OOM，每页查询条数太大才可能会。

**Comment by xiejinsong** [comment]
3.6版分页查询初始化SearchResult并没有初始化dataList长度，升级到3.8.1初始化SearchResult会初始化dataList长度大小为totalCount，ArrayList内部初始化数组会占用16 + totalCount * 4

SearchResult<T> result = new SearchResult<>(totalCount, summaries);
BeanMeta<T> beanMeta = searchSql.getBeanMeta();
SqlResult.ResultSet listResult = sqlResult.getListResult();

public SearchResult(Number totalCount, Number[] summaries) {
      this(new ArrayList<>(totalCount.intValue()));
      this.totalCount = totalCount;
      this.summaries = summaries;
  }

**Comment by troyzhxu** [comment]
多谢反馈，马上修复

**Comment by troyzhxu** [comment]
v3.8.2 已发布，修复了该问题。

**Comment by xiejinsong** [comment]
感谢，前段时间适配到aliyun ots多元索引，大大提升了开发效率。最近打算参考cube.js，将beansearcher做成olap引擎与前端的粘粘层。很棒～
