### ISSUE TITLE
如何实现字典回写

### ISSUE THREAD

**Issue by g88827929g** [troyzhxu/bean-searcher#67]
如何将数据库查询出来的值转为字典值

**Comment by troyzhxu** [comment]
可以在 结果过滤器中 处理这个逻辑：
https://bs.zhxu.cn/guide/latest/advance.html#%E7%BB%93%E6%9E%9C%E8%BF%87%E6%BB%A4%E5%99%A8%EF%BC%88v3-6-0%EF%BC%89

或者再集成一个第三方字典翻译也是可以的。
