### ISSUE TITLE
[Feature Request] Json serialize/deserialize

### ISSUE THREAD

**Issue by aboutZZ** [troyzhxu/bean-searcher#68]
希望可以增加数据库字段 json 序列化/反序列化功能
例如数据库某字段存储为 `json` 格式，读取时自动反序列化为对应的`POJO`类，存储时自动序列化为`json`字符串后存入数据库。

**Comment by troyzhxu** [comment]
自定义一个字段转换器即可：
https://bs.zhxu.cn/guide/latest/advance.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BD%AC%E6%8D%A2%E5%99%A8

**Comment by troyzhxu** [comment]
v4.x 版本已经自带了 `JsonFieldConvertor `
https://github.com/troyzhxu/bean-searcher/releases
