### ISSUE TITLE
Map入参数怎么使用swagger,才能看到字段名?

### ISSUE THREAD

**Issue by 472012723** [troyzhxu/bean-searcher#72]
如题Map入参数怎么使用swagger,才能看到字段名?

**Comment by troyzhxu** [comment]
目前 Map 参数目前不直接支持渲染 swagger 文档参数，但可以这样：

![image](https://user-images.githubusercontent.com/29403889/224876613-544a3617-1294-47b5-a5be-19eab98a8db8.png)
