### ISSUE TITLE
使用自定义运算符替换Equal后，字段导致不写op=eq，不会出现在sql语句中

### ISSUE THREAD

**Issue by zengyufei** [troyzhxu/bean-searcher#73]
### 问题描述

使用自定义运算符替换Equal后，字段导致不写op=eq，不会出现在sql语句中，经排查，是 DefaultParamResolver#allowedOperator 方法里面写死了默认使用 FieldOps.Equal ，替换后，已经不存在Equal。导致字段不参与sql。 

### 复现步骤

1. http://localhost/test/project?id=1

### 期望结果

返回id为1的数据。

期望sql：select * from project where id=1;

### 实际结果

返回全表数据。

实际sql：select * from project;

### 环境信息

- 操作系统：win10
- 浏览器：edge
- bs版本： 4.1.2

### 补充说明

没有了

**Comment by troyzhxu** [comment]
v4.2.0 已修复：https://github.com/troyzhxu/bean-searcher/releases/tag/v4.2.0
