### ISSUE TITLE
左、右连接中动态查询条件的添加

### ISSUE THREAD

**Issue by iamshifty** [troyzhxu/bean-searcher#77]
目前左、右连接在bean中都是写好的，如何在其中添加动态查询条件，比如下面代码中可实现与角色表的内连接
@SearchBean(tables = "user u inner join role r on u.role_id = r.id") 
public class User {
    // ...
}
在实际应用场景中，可能会有下面情况
@SearchBean(tables = "user u inner join role r on u.role_id = r.id and r.xx=xx and r.xxx=xxx") 
public class User {
    // ...
}
其中r.xx和r.xxx在不同的条件下才会应用，如果用内嵌参数到是可以部分解决，比如
@SearchBean(tables = "user u inner join role r on u.role_id = r.id :roleJoin:") 
public class User {
    // ...
}
但roleJoin这个参数还要自己拼才行，有没有办法解决？

**Comment by troyzhxu** [comment]
如果这个条件可以放到 where 里，则把 `r.xx` 与 `r.xxx` 做成 SeachBean 的字段，或放在 `@SeachBean.fields` 即可。

如果不能放到 where 里，则目前只能用 拼接参数 自己拼。

`v4.4` 版本会 引入条件模板 功能：https://github.com/troyzhxu/bean-searcher/issues/54，那时候就不用手动拼了。
