### ISSUE TITLE
分组字段能否支持动态传入

### ISSUE THREAD

**Issue by flyingdew** [troyzhxu/bean-searcher#78]
分组字段通过groupBy参数传入

**Comment by troyzhxu** [comment]
可以，使用 拼接参数：
https://bs.zhxu.cn/guide/latest/bean.html#%E5%B5%8C%E5%85%A5%E5%8F%82%E6%95%B0
https://bs.zhxu.cn/guide/latest/bean.html#%E5%B5%8C%E5%85%A5%E5%88%B0-searchbean-groupby
