### ISSUE TITLE
对于同一个属性的多个运算符如何指定

### ISSUE THREAD

**Issue by iamshifty** [troyzhxu/bean-searcher#79]
比如像 a >= 0 and a<=10这种该如何设置参数

**Comment by troyzhxu** [comment]
# 方法一：
最简单
```java
MapUtils.builder()
    .field(User::getAge).sql("$1 >= 0 and $1 <= 10")
   .build();
```
参考：https://bs.zhxu.cn/guide/latest/params.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9D%A1%E4%BB%B6%EF%BC%88since-v3-8%EF%BC%89
# 方法二：
自定义运算符（一劳永逸）
参考：https://bs.zhxu.cn/guide/latest/advance.html#%E7%8E%A9%E8%BD%AC%E8%BF%90%E7%AE%97%E7%AC%A6%EF%BC%88since-v3-3-0%EF%BC%89
# 方法三
逻辑分组（只适用于前端控制参数）
参考：https://bs.zhxu.cn/guide/latest/params.html#%E9%80%BB%E8%BE%91%E5%88%86%E7%BB%84%EF%BC%88since-v3-5%EF%BC%89
