### ISSUE TITLE
spring boot 3執行時, bean searcher 會報錯

### ISSUE THREAD

**Issue by vt167098** [troyzhxu/bean-searcher#82]
版本為spring boot 3.1.2, jdk版本 17, bean searcher 版本4.1.2

在spring boot 2.7的時候都很正常(使用bean searcher 3.8.2版本)
最近在測試sping boot 3, 發現有問題, 我是使用mybatis + druid的方式連線

`***************************
APPLICATION FAILED TO START
***************************

Description:

Field beanSearcher in com.vt.demo23.controller.FrontEndController required a bean of type 'cn.zhxu.bs.BeanSearcher' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'cn.zhxu.bs.BeanSearcher' in your configuration.

`

我的寫法跟spring boot 2.7的寫法一致.

**Comment by troyzhxu** [comment]
请确认使用的是否是  `cn.zhxu:bean-searcher-boot-starter` 依赖？

**Comment by vt167098** [comment]
spring boot 3.2.2 + bean-searcher 4.2.7,確認已經可以運作,沒有問題.
