### ISSUE TITLE
 can you split sub module “beanSearcher-annotation” ?

### ISSUE THREAD

**Issue by shen0834** [troyzhxu/bean-searcher#86]
能否拆一个 annotation 的工程出来？

因为 beansearcher 一些查询的 view 对象，是放在 api 里面作为定义pojo 包里的，不希望再 api 里依赖 beanSearcher 的所有包

**Comment by troyzhxu** [comment]
Bean Searcher 一共两个包：
* `cn.zhxu:bean-searcher`
* `cn.zhxu:bean-searcher-boot-starter`
* `cn.zhxu:bean-searcher-solon-plugin`

在你的 `api` 模块里，这样即可：

```
compileOnly 'cn.zhxu:bean-searcher'
```
