### ISSUE TITLE
数据权限问题处理

### ISSUE THREAD

**Issue by jingsewu** [troyzhxu/bean-searcher#87]
请问下有什么好的方式来处理数据权限的问题。比如普通用户不能查询用户列表，权限菜单等数据。

**Comment by troyzhxu** [comment]
> > 请问下有什么好的方式来处理数据权限的问题。比如普通用户不能查询用户列表，权限菜单等数据。
> 
> 追加描述：我是前端封装了一个通用的组件来构建查询条件 & 查询对象，后端只提供了一个接口。所以现在没办法通过接口来进行权限控制。
> 
> 目前我想到的方法是：在权限系统/菜单上增加此权限能操作的表，然后根据用户可以操作的表来验证是否有查询权限。

虽然只有一个查询接口，单你的接口里应该有一个查询类型吧，比如 `queryType=menus` 表示查询菜单，只要有这个参数，你就可以使用该参数进行权限判断，判断通过后再 调用 Bean Searcher 的检索接口。

**Comment by troyzhxu** [comment]
> 这里可以使用到拦截器来实现。但是目前没有提供BeanMeta的修改的方法，或者SearchSql对象上能否提供一个修改where条件的方法。

在 Sql 拦截器里，你可以构造一个新的 `SearchSql` 对象返回，也就是说它里面的任何值可以修改。

**Comment by jingsewu** [comment]
> > > 请问下有什么好的方式来处理数据权限的问题。比如普通用户不能查询用户列表，权限菜单等数据。
> > 
> > 
> > 追加描述：我是前端封装了一个通用的组件来构建查询条件 & 查询对象，后端只提供了一个接口。所以现在没办法通过接口来进行权限控制。
> > 目前我想到的方法是：在权限系统/菜单上增加此权限能操作的表，然后根据用户可以操作的表来验证是否有查询权限。
> 
> 虽然只有一个查询接口，单你的接口里应该有一个查询类型吧，比如 `queryType=menus` 表示查询菜单，只要有这个参数，你就可以使用该参数进行权限判断，判断通过后再 调用 Bean Searcher 的检索接口。

因为前端可能会伪造请求，所以需要在sql层面做一些过滤。不能完全根据前端传递的queryType来判断
