### ISSUE TITLE
建议增加前端可以控制是否分页的参数，比如分页大小参数pageSize=0时

### ISSUE THREAD

**Issue by flyingdew** [troyzhxu/bean-searcher#90]

**Comment by troyzhxu** [comment]
不分页查询全部使用 `searchAll(..)` 方法

**Comment by troyzhxu** [comment]
不需要返回总条数信息 使用 `searchList(..)` 方法

**Comment by flyingdew** [comment]
我的意思是同一个接口，可以分页，也可以不分页，分页与否由调用方决定。

**Comment by troyzhxu** [comment]
> 我的意思是同一个接口，可以分页，也可以不分页，分页与否由调用方决定。

那你的接口内部 if else 一下即可，查询全部是一个危险操作，作为一个以直接处理外部参数为主要开发模式的查询框架，直接提供这样的参数不太安全。
