### ISSUE TITLE
根据用户的请求参数，决定是否去重（distinct）

### ISSUE THREAD

**Issue by vt167098** [troyzhxu/bean-searcher#91]
目前去重distinct是在@SearchBean(distinct=true)中設定, 能否增加去重功能是可以在每個查詢中決定啟動或關閉?

**Comment by troyzhxu** [comment]
目前不可以，有什么场景需要这么做吗？

**Comment by vt167098** [comment]
就是實際使用上提供給使用者自行決定這個查詢要不要做distinct(要做distinct就會合併有輸出的欄位, 不做distinct就會得到完整的查詢筆數資料), 算是我自己應用上的一個特殊需求, 謝謝.

**Comment by troyzhxu** [comment]
那自定义 `SqlResolver` 组件，就能实现你的需求了

**Comment by vt167098** [comment]
您好, 我還是不知道要從何下手, 我如果有多個entity都要從前端來決定這個查詢是要去重或不要去重, 應該要怎麼做, 我目前是同樣的entity建立兩個, 其中一個在SearchBean有啟用distinct=true的方式來處理.

謝謝.

**Comment by troyzhxu** [comment]
> 就是實際使用上提供給使用者自行決定這個查詢要不要做distinct(要做distinct就會合併有輸出的欄位, 不做distinct就會得到完整的查詢筆數資料), 算是我自己應用上的一個特殊需求, 謝謝.

可以举个例子吗？

**Comment by vt167098** [comment]
学生成绩的实体类如下:

@SearchBean(tables="course")
public class Course {
    @DbField("id")
    private Integer id;

    @DbField("name")
    private String name;

    @DbField("age")
    private Short age;

    @DbField("course")
    private String course;

    @DbField("score")
    private Short score;
}

资料如下:
[
	{id: 1, name: 'john', age: 18, course: 'English', score: 90},
	{id: 1, name: 'john', age: 18, course: 'Math', score: 80},
	{id: 1, name: 'john', age: 18, course: 'History', score: 95},
	{id: 1, name: 'john', age: 18, course: 'Chinese', score: 100},
	{id: 2, name: 'mary', age: 17, course: 'English', score: 90},
	{id: 2, name: 'mary', age: 17, course: 'Math', score: 90},
	{id: 2, name: 'mary', age: 17, course: 'History', score: 90},
	{id: 2, name: 'mary', age: 17, course: 'Chinese', score: 90},
	{id: 3, name: 'joe', age: 17, course: 'English', score: 90},
	{id: 3, name: 'joe', age: 17, course: 'Math', score: 90},
	{id: 3, name: 'joe', age: 17, course: 'History', score: 90},
	{id: 3, name: 'joe', age: 17, course: 'Chinese', score: 90},
	{id: 4, name: 'mark', age: 17, course: 'English', score: 90},
	{id: 4, name: 'mark', age: 17, course: 'Math', score: 90},
	{id: 4, name: 'mark', age: 17, course: 'History', score: 90},
	{id: 4, name: 'mark', age: 17, course: 'Chinese', score: 90}
]

我下查询用onlySelect(id, name)且不下其他条件，当在注释没有声明distinct=true的时，输出笔数会是16笔，如果有声明distinct=true，输出笔数会是4笔。

在我应用的情境中, 要输出的栏位是给前端user自行挑选的, 我将挑选的栏位放入onlySelect回传至beanSearch, 当然我也可以
强迫都启动去重, 但我还是希望是否去重可以由user来决定.

所以我目前的做法就是每个实体都建立两个,一个有启动去重一个没有的方式来处理.

不知这样的例子可以吗?

**Comment by troyzhxu** [comment]
自定义 `SqlResolver` 组件，代码如下（根据请求参数 `paraMap` 中是否包含 `distinct` 参数来决定是否去重）：

```java
@Bean
public SqlResolver mySqlResolver(Dialect dialect, ObjectProvider<GroupPair.Resolver> groupPairResolver,
                               ObjectProvider<JoinParaSerializer> joinParaSerializer) {
    DefaultSqlResolver resolver = new DefaultSqlResolver(dialect) {
        @Override
        protected <T> SqlWrapper<Object> buildFieldSelectSql(BeanMeta<T> beanMeta, List<String> fetchFields, Map<String, Object> paraMap) {
            SqlWrapper<Object> sqlWrapper = super.buildFieldSelectSql(beanMeta, fetchFields, paraMap);
            String sql = sqlWrapper.getSql();
            if (paraMap.containsKey("distinct") && !sql.contains("select distinct")) {
                // 如果用户的请求参数中包含 distinct，且 sql 中没有 distinct
                String newSql = sql.replace("select ", "select distinct ");
                sqlWrapper.setSql(newSql);
            }
            return sqlWrapper;
        }
    };
    ifAvailable(groupPairResolver, resolver::setGroupPairResolver);
    ifAvailable(joinParaSerializer, resolver::setJoinParaSerializer);
    return resolver;
}
```
